### PR TITLE
Support -Wext-lambda-captures-this option for cuda 11

### PR DESCRIPTION
**Pull request by Char-Aznable**
See https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#generic-tool-options-Wext-lambda-captures-this

### CODE REVIEW

**Comment by Char-Aznable** [comment]
@jjwilke

**Comment by masterleinad** [comment]
The up-to-date version for nvcc_wrapper is https://github.com/kokkos/kokkos/blob/develop/bin/nvcc_wrapper and that supports `-Wext-lambda-captures-this`.

**Comment by Char-Aznable** [comment]
I see. I have some code that accidentally uses my local checkout of this repo. BTW, is this repo no longer maintained?

**Comment by jjwilke** [comment]
It is not. Recent change, though. We just changed the way we handle nvcc_wrapper inside of Spack.

**Comment by Char-Aznable** [comment]
OK. I will close this for now.

**Pull request closed without merging**
