### PR TITLE
Addresses a Bug with Architecture Specific Code Generation Flags

### PR DESCRIPTION
**Pull request by nmhamster**
NVCC errors without these adjustments as parameters are expected.

### CODE REVIEW

**Comment by nmhamster** [comment]
Addresses issues in #14.

**Comment by ibaned** [comment]
@nmhamster can you remove the debug line?
```bash
echo "CUDA: $cuda_args"
```
otherwise, looks good

**Comment by nmhamster** [comment]
@ibaned - done. Thanks for looking so quickly!

**Comment by nmhamster** [comment]
@ibaned - can we get the PR merged soon please, this is need for ATDM.

**Comment by ibaned** [comment]
Whoops, yea it just slipped my mind.

**Pull request merged**
